name: Lint | Build | Deploy to Production

on:
    push:
        branches:
            - main
        paths:
            - "lens-view/**"

env:
    NODE_LTS_VERSION: 22
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    SKIP_ENV_VALIDATION: true

jobs:
    lint_build:
        name: Lint and Build
        runs-on: blacksmith-4vcpu-ubuntu-2404
        defaults:
            run:
                working-directory: ./lens-view
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  package_json_file: lens-view/package.json
                  run_install: false

            - name: Setup Node v${{ env.NODE_LTS_VERSION }}
              uses: useblacksmith/setup-node@v5
              with:
                  node-version: ${{ env.NODE_LTS_VERSION }}
                  cache: pnpm
                  cache-dependency-path: ./lens-view/pnpm-lock.yaml

            - name: Install Dependencies
              run: |
                  echo "Installing Dependencies..."
                  pnpm install --frozen-lockfile

            - name: Pull Vercel Environment Information
              run: |
                  pnpx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project
              run: |
                  echo "Building..."
                  pnpx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project to Production
              run: |
                  echo "🎉 Deploying..."
                  pnpx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --no-wait
